### ISSUE TITLE
首页简介优化

### ISSUE THREAD

**Issue by dengn** [matrix-dc/docs#10]
这个页面太简单了。

<img width="863" alt="image" src="https://github.com/matrix-dc/docs/assets/4965857/9d57f27e-8b43-46e7-b05b-31eafbb31200">

需要简单的介绍下Neolink.ai平台和使用场景。

然后把一些基本和重要的文档导航，小助手联系方式也摆出来。

**Comment by LiuYuqi77** [comment]
已在 https://github.com/matrix-dc/docs/pull/15 解决，intro页补充：1.neolink.ai介绍 2.使用场景 3.文档推荐（必看/常用文档） 4.联系我们
