### ISSUE TITLE
联系我们直接放小助手二维码

### ISSUE THREAD

**Issue by dengn** [matrix-dc/docs#8]
<img width="872" alt="image" src="https://github.com/matrix-dc/docs/assets/4965857/556873f0-3822-4e3c-8bef-2047c28f4e12">
这里不要让用户又跳到Neolink.ai上去，而是直接给它小助手二维码完成闭环。

**Comment by LiuYuqi77** [comment]
已在 https://github.com/matrix-dc/docs/pull/14 中删除跳到neolink.ai的逻辑，增加小助手二维码完成闭环
